### ISSUE TITLE
您好，请问还有多久公布代码

### ISSUE THREAD

**Issue by gonownow** [Leon-Francis/Multi-Modal-Stance-Detection#1]

**Comment by Leon-Francis** [comment]
感谢你对我们工作的关注，目前代码和数据已经开源，如果后续有问题欢迎进行交流。

**Comment by gonownow** [comment]
> 感谢你对我们工作的关注，目前代码和数据已经开源，如果后续有问题欢迎进行交流。

请问可以公布开源数据集中gpt4v_cot_response的内容吗.

**Comment by Leon-Francis** [comment]
因为这样的CoT对应着每条推文，并且和文本以及图片内容强相关，我们认为开源这部分内容可能会违反隐私协议。在最新的提交 9fa8601 中，我们开源了获取GPT4-Vision CoT的代码和指令，你可以尝试通过我们的代码来自行获取。

**Comment by gonownow** [comment]
你好，感谢您的回复，对于开源数据集尝试使用id进行获取，但是发现有大量推特中图片失效，在MTWQ由于一些因素
的tarin前100数据出现百分之五十图片失效的情况，请问完整数据集是否可以私下进行交流学习使用。期待您的回复
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Leon-Francis/Multi-Modal-Stance-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月10日(星期一) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Leon-Francis/Multi-Modal-Stance-Detection] 您好，请问还有多久公布代码 (Issue #1)





 
因为这样的CoT对应着每条推文，并且和文本以及图片内容强相关，我们认为开源这部分内容可能会违反隐私协议。在最新的提交 9fa8601 中，我们开源了获取GPT4-Vision CoT的代码和指令，你可以尝试通过我们的代码来自行获取。

**Comment by gonownow** [comment]
> 因为这样的CoT对应着每条推文，并且和文本以及图片内容强相关，我们认为开源这部分内容可能会违反隐私协议。在最新的提交 [9fa8601](https://github.com/Leon-Francis/Multi-Modal-Stance-Detection/commit/9fa8601bc4ced1aee0d0d76a5d7bf3d85415a64d) 中，我们开源了获取GPT4-Vision CoT的代码和指令，你可以尝试通过我们的代码来自行获取。

你好我在尝试通过id获取数据图片时发现大量图片失效的情况，在MTWQ数据train前100个数据集样例中出现大于一半以上数据集图片失效的问题，在其它数据集中也出现这种情况，请问是否可以公开图片数据集。非常期待您的回复。

**Comment by Leon-Francis** [comment]
你好，确实会有一部分样本由于原发布者删除、修改了推文，或者更改了推文的可见性，导致样本无法再被完整获取。在我随机采样的20个MTWQ数据中发现有9个被删除或者更改了。对这个问题我非常抱歉，这也是很多twitter数据工作都会遇到的问题。你可以和我联系来解决这个问题：angli@stu.hit.edu.cn
