### ISSUE TITLE
数据爬取问题

### ISSUE THREAD

**Issue by sukeey** [Leon-Francis/Multi-Modal-Stance-Detection#3]
您好，我在爬取数据时发现有些数据是对另一个推文的转发+评论，该条数据并不涉及到图片，请问这类数据如何处理
<img width="305" alt="59c79f43932fb9a90fc908ed4683e37" src="https://github.com/Leon-Francis/Multi-Modal-Stance-Detection/assets/50063094/d9177376-bc5f-4d1d-aa96-b220c660b705">

**Comment by Leon-Francis** [comment]
你好，感谢你对我们工作的关注。
这个问题是源于我们的数据收集工具会把被转发推文中的多媒体信息作为该推文的内容一起进行收集。这本身不会导致问题，因为对于被转发推文的评论和被转发推文是相关的。但是我们发现被转发推文中用户的profile image有时也会作为图片被进行收集。尽管我们在标注过程中提醒标注者将这种带有无意义的图片的样本进行删除，但是可能有一部分剩余了下来。
如果你在构造我们的数据集的过程中遇到问题，可以联系：angli@stu.hit.edu.cn

**Comment by rain-in-night** [comment]
> 您好，我在爬取数据时发现有些数据是对另一个推文的转发+评论，该条数据并不涉及到图片，请问这类数据如何处理 <img alt="59c79f43932fb9a90fc908ed4683e37" width="305" src="https://private-user-images.githubusercontent.com/50063094/339950437-d9177376-bc5f-4d1d-aa96-b220c660b705.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwNzkzNTksIm5iZiI6MTc3NzA3OTA1OSwicGF0aCI6Ii81MDA2MzA5NC8zMzk5NTA0MzctZDkxNzczNzYtYmM1Zi00ZDFkLWFhOTYtYjIyMGM2NjBiNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI1VDAxMDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMGQzMzRlYWQzYTQyNDJmMjNkMjVkZGNjOWFmYmNhZTI0M2FkZWMzNTRjZmI2NGNlYzAwZjY4NzI1ZmYwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.K6hIDjvLwuUUqSlmF7M-5QBLe9l8VSyZmeq65NZ17yc">

您好！冒昧打扰，想向您咨询一下，您当年是否成功获取 / 爬取到了这份数据集的原始数据？
由于时间过去较久，原平台上的大量推文已被删除，仅靠提供的 tweet ID 已经无法完整复原数据。如果您这边还保留着可用的原始数据，我非常希望能向您请求分享，我愿意为此提供一定的酬劳，以感谢您的帮助。
给您添麻烦了，非常感谢！
