### ISSUE TITLE
请问可以上传爬取推特数据集的代码吗

### ISSUE THREAD

**Issue by gonownow** [Leon-Francis/Multi-Modal-Stance-Detection#4]

**Comment by Leon-Francis** [comment]
这个在[Tweepy](https://github.com/tweepy/tweepy) and [twarc](https://twarc-project.readthedocs.io/en/latest/twarc2_en_us/)的相关文档中都有示例，不是很复杂，请参考他们的文档。困难可能在于需要申请Twitter developer account。

**Comment by 18133751506** [comment]
感谢老师的分享！但是我有一个问题，我看到访问该数据集进行hydrate需要较多tweet的limitation，除了购买专业版的developer账号，有没有其他免费的办法
