### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by PowerLittleYin** [Leon-Francis/Multi-Modal-Stance-Detection#5]
老师您好，感谢您的工作与开源。在运行代码中我遇到了一些问题，碍于水平我找不出来..我只运行的textual的baseline，您代码中的configuration我都没用动，但是在训练完之后，我发现train_loss每一轮都是从头开始训练，而不是从上一轮训练之后的loss继续训练，所以他的trainloss是周期震荡的，而且可能也因此导致了验证集和测试集的loss震荡不收敛，请问这是代码中的问题吗？不知道有没有朋友遇到相同的问题...

**Comment by Leon-Francis** [comment]
您好，我的代码应该没有涉及对同一模型进行多轮训练的过程，您提及的多轮训练可能是指对于每个实验我们会采用五个不同的随机种子进行五次实验，并最终报告五次实验的平均结果。如果您不希望跑多次实验的话可以修改这里的设置：[in-target](https://github.com/Leon-Francis/Multi-Modal-Stance-Detection/blob/9fa8601bc4ced1aee0d0d76a5d7bf3d85415a64d/config/tmpt_config.yaml#L5) and [zero-shot](https://github.com/Leon-Francis/Multi-Modal-Stance-Detection/blob/9fa8601bc4ced1aee0d0d76a5d7bf3d85415a64d/config/tmpt_config.yaml#L36)
